In [152]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [153]:
train = pd.read_csv("./DACONLG/train.csv")
train.head()

ID    X_01     X_02   X_03  X_04     X_05    X_06   X_07    X_08  \
0  TRAIN_00001  70.544  103.320  67.47     1  101.892  74.983  29.45   62.38   
1  TRAIN_00002  69.524  103.321  65.17     1  101.944  72.943  28.73   61.23   
2  TRAIN_00003  72.583  103.320  64.07     1  103.153  72.943  28.81  105.77   
3  TRAIN_00004  71.563  103.320  67.57     1  101.971  77.022  28.92  115.21   
4  TRAIN_00005  69.524  103.320  63.57     1  101.981  70.904  29.68  103.38   

     X_09  ...    Y_05    Y_06   Y_07    Y_08    Y_09    Y_10    Y_11    Y_12  \
0  245.71  ...  29.632  16.083  4.276 -25.381 -25.529 -22.769  23.792 -25.470   
1  233.61  ...  33.179  16.736  3.229 -26.619 -26.523 -22.574  24.691 -26.253   
2  272.20  ...  31.801  17.080  2.839 -26.238 -26.216 -22.169  24.649 -26.285   
3  255.36  ...  34.503  17.143  3.144 -25.426 -25.079 -21.765  24.913 -25.254   
4  241.46  ...  32.602  17.569  3.138 -25.376 -25.242 -21.072  25.299 -25.072   

     Y_13    Y_14  
0 -25.409 -25.304  
1 -26.497 -26.438  
2 -26.215 -26.370  
3 -25.021 -25.345  
4 -25.195 -24.974  

[5 rows x 71 columns]

In [154]:
train = train.drop(["ID", "X_03", "X_23", "X_47", "X_48"], axis=1)

In [155]:
train_1 = train.iloc[:14771, :]
train_1

X_01     X_02  X_04     X_05    X_06   X_07    X_08    X_09  X_10  \
0      70.544  103.320     1  101.892  74.983  29.45   62.38  245.71   0.0   
1      69.524  103.321     1  101.944  72.943  28.73   61.23  233.61   0.0   
2      72.583  103.320     1  103.153  72.943  28.81  105.77  272.20   0.0   
3      71.563  103.320     1  101.971  77.022  28.92  115.21  255.36   0.0   
4      69.524  103.320     1  101.981  70.904  29.68  103.38  241.46   0.0   
...       ...      ...   ...      ...     ...    ...     ...     ...   ...   
14766  75.642  103.320     1  103.158  76.002  29.87  248.51  241.89   0.0   
14767  66.465  103.320     1  102.035  70.904  26.99  103.92  273.39   0.0   
14768  73.603  103.320     1  103.159  73.963  29.15  103.69  294.73   0.0   
14769  76.662  103.320     1  103.156  77.022  29.41  103.79  266.16   0.0   
14770  69.524  103.320     1  103.139  69.884  28.68  102.35  266.04   0.0   

       X_11  ...    Y_05    Y_06   Y_07    Y_08    Y_09    Y_10    Y_11  \
0       0.0  ...  29.632  16.083  4.276 -25.381 -25.529 -22.769  23.792   
1       0.0  ...  33.179  16.736  3.229 -26.619 -26.523 -22.574  24.691   
2       0.0  ...  31.801  17.080  2.839 -26.238 -26.216 -22.169  24.649   
3       0.0  ...  34.503  17.143  3.144 -25.426 -25.079 -21.765  24.913   
4       0.0  ...  32.602  17.569  3.138 -25.376 -25.242 -21.072  25.299   
...     ...  ...     ...     ...    ...     ...     ...     ...     ...   
14766   0.0  ...  29.741  16.326  3.322 -26.673 -26.611 -22.414  24.002   
14767   0.0  ...  30.486  16.911  2.528 -26.368 -26.479 -21.948  24.483   
14768   0.0  ...  27.185  14.739  3.850 -27.929 -28.054 -24.098  22.263   
14769   0.0  ...  32.186  15.963  2.930 -26.746 -26.845 -22.708  23.655   
14770   0.0  ...  28.749  14.503  3.878 -28.253 -28.513 -24.634  22.053   

         Y_12    Y_13    Y_14  
0     -25.470 -25.409 -25.304  
1     -26.253 -26.497 -26.438  
2     -26.285 -26.215 -26.370  
3     -25.254 -25.021 -25.345  
4     -25.072 -25.195 -24.974  
...       ...     ...     ...  
14766 -26.746 -26.638 -26.749  
14767 -26.442 -26.449 -26.342  
14768 -28.184 -27.977 -28.049  
14769 -26.827 -26.916 -26.921  
14770 -28.171 -28.141 -28.110  

[14771 rows x 66 columns]

In [156]:
train_2 = train.iloc[14771:, :]
train_2

X_01     X_02  X_04     X_05    X_06   X_07    X_08    X_09  X_10  \
14771  68.504  103.320     1  102.015  70.904  28.34  110.56  259.61   0.0   
14772  75.642  103.320     1  103.154  76.002  28.93  124.76  248.36   0.0   
14773  69.524  103.320     1  102.011  70.904  29.32   77.89  242.15   0.0   
14774  70.544  103.320     1  101.946  72.943  28.88  113.97  236.33   0.0   
14775  71.563  103.320     1  103.156  71.923  29.51  123.33  262.31   0.0   
...       ...      ...   ...      ...     ...    ...     ...     ...   ...   
39602  66.465  103.320     1  103.150  66.825  30.20   77.83  298.05   0.0   
39603  66.465  103.321     1  102.021  66.825  29.21  102.25  270.67   0.0   
39604  68.504  103.320     1  103.144  68.864  29.96  102.61  198.07   0.0   
39605  66.465  103.320     1  102.025  67.845  30.30  112.60  275.52   0.0   
39606  66.465  103.320     1  102.004  69.884  30.16  112.90  276.06   0.0   

       X_11  ...    Y_05    Y_06   Y_07    Y_08    Y_09    Y_10    Y_11  \
14771   0.0  ...  32.081  16.763  3.157 -25.469 -25.430 -21.838  24.923   
14772   0.0  ...  32.547  16.591  3.313 -26.185 -26.169 -22.299  24.478   
14773   0.0  ...  33.820  17.038  2.966 -25.899 -25.723 -21.665  25.022   
14774   0.0  ...  33.714  17.819  2.843 -25.515 -25.848 -21.092  25.676   
14775   0.0  ...  31.163  16.968  3.069 -25.688 -25.674 -21.746  24.778   
...     ...  ...     ...     ...    ...     ...     ...     ...     ...   
39602   0.0  ...  29.194  16.582  3.410 -26.486 -26.581 -22.772  24.261   
39603   0.0  ...  29.859  15.659  3.406 -27.308 -27.203 -24.674  23.427   
39604   0.0  ...  24.720  16.823  3.215 -26.502 -26.687 -22.577  24.301   
39605   0.0  ...  26.412  15.757  4.216 -26.760 -26.634 -24.066  23.305   
39606   0.0  ...  30.745  16.781  3.307 -26.054 -26.251 -23.257  24.450   

         Y_12    Y_13    Y_14  
14771 -25.534 -25.384 -25.521  
14772 -26.102 -26.126 -26.141  
14773 -25.493 -25.656 -25.781  
14774 -25.656 -25.676 -25.584  
14775 -25.957 -25.784 -25.709  
...       ...     ...     ...  
39602 -26.491 -26.584 -26.580  
39603 -27.250 -27.334 -27.325  
39604 -26.388 -26.425 -26.601  
39605 -26.536 -26.751 -26.635  
39606 -26.224 -26.256 -26.093  

[24836 rows x 66 columns]

In [157]:
X_train_1 = train_1.iloc[:, :52]
y_train_1 = train_1.iloc[:, 52:]

X_train_2 = train_2.iloc[:, :52]
y_train_2 = train_2.iloc[:, 52:]

X_train_1.head()

X_01     X_02  X_04     X_05    X_06   X_07    X_08    X_09  X_10  X_11  \
0  70.544  103.320     1  101.892  74.983  29.45   62.38  245.71   0.0   0.0   
1  69.524  103.321     1  101.944  72.943  28.73   61.23  233.61   0.0   0.0   
2  72.583  103.320     1  103.153  72.943  28.81  105.77  272.20   0.0   0.0   
3  71.563  103.320     1  101.971  77.022  28.92  115.21  255.36   0.0   0.0   
4  69.524  103.320     1  101.981  70.904  29.68  103.38  241.46   0.0   0.0   

   ...  X_45  X_46      X_49        X_50        X_51        X_52        X_53  \
0  ...  0.29  1463   9706.03  137.043591  135.359219  147.837968  134.313475   
1  ...  0.13  1463  10423.43  133.736691  135.979817  149.924692  123.630583   
2  ...  0.14  1468  10948.53  132.805112  131.055355  146.814592  128.939070   
3  ...  0.22  1469  15007.03  134.138760  133.239422  139.720132  132.260824   
4  ...  0.22  1469  11051.03  142.728970  136.620022  134.853555  134.760252   

         X_54        X_55        X_56  
0  125.605427  136.721425  125.028256  
1  127.893337  143.322659  124.877308  
2  127.012195  140.395688  122.238232  
3  130.723186  147.624829  134.875225  
4  125.647793  139.331105  123.272762  

[5 rows x 52 columns]

In [158]:
import sklearn
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train_1_scaled = ss.fit_transform(X_train_1)
X_train_2_scaled = ss.fit_transform(X_train_2)

In [159]:
y_train_1.head()

Y_01   Y_02   Y_03    Y_04    Y_05    Y_06   Y_07    Y_08    Y_09    Y_10  \
0  2.056  1.456  1.680  10.502  29.632  16.083  4.276 -25.381 -25.529 -22.769   
1  1.446  1.184  1.268  18.507  33.179  16.736  3.229 -26.619 -26.523 -22.574   
2  1.251  0.665  0.782  14.082  31.801  17.080  2.839 -26.238 -26.216 -22.169   
3  1.464  1.079  1.052  16.975  34.503  17.143  3.144 -25.426 -25.079 -21.765   
4  0.983  0.646  0.689  15.047  32.602  17.569  3.138 -25.376 -25.242 -21.072   

     Y_11    Y_12    Y_13    Y_14  
0  23.792 -25.470 -25.409 -25.304  
1  24.691 -26.253 -26.497 -26.438  
2  24.649 -26.285 -26.215 -26.370  
3  24.913 -25.254 -25.021 -25.345  
4  25.299 -25.072 -25.195 -24.974

In [160]:
X_test = pd.read_csv("./DACONLG/test.csv")
X_test.head()

ID    X_01     X_02   X_03  X_04     X_05    X_06   X_07    X_08  \
0  TEST_00001  68.504  103.321  76.67     1  101.867  73.963  30.51   63.57   
1  TEST_00002  67.485  103.320  69.37     1  101.992  67.845  28.03  116.99   
2  TEST_00003  69.524  103.320  68.97     1  101.884  77.022  29.65  205.68   
3  TEST_00004  69.524  103.320  65.87     1  101.866  73.963  28.15  103.38   
4  TEST_00005  73.603  103.321  66.67     1  101.891  74.983  29.92   71.20   

     X_09  ...  X_47  X_48      X_49        X_50        X_51        X_52  \
0  239.80  ...     1     1  17227.63  138.130429  129.460682  141.506570   
1  189.23  ...     1     1  17134.53  136.148839  128.266277  145.911745   
2  214.93  ...     1     1  14860.83  120.447446  119.988804  132.099908   
3  180.80  ...     1     1  15252.53  133.994695  125.069180  147.507669   
4  231.93  ...     1     1  10752.23  137.918202  135.116192  138.600473   

         X_53        X_54        X_55        X_56  
0  133.427229  129.711498  133.138096  121.859684  
1  131.196417  132.411480  133.629025  124.178623  
2  120.450155  130.051708  128.252972  114.475628  
3  123.142653  125.963665  139.666592  126.589253  
4  127.173033  137.252712  134.411335  124.020016  

[5 rows x 57 columns]

In [161]:
X_test = X_test.drop(["ID", "X_03", "X_23", "X_47", "X_48"], axis=1)

In [162]:
X_test_1 = X_test.iloc[:14771, :]
X_test_2 = X_test.iloc[14771:, :]

In [163]:
X_test_1_scaled = ss.fit_transform(X_test_1)
X_test_2_scaled = ss.fit_transform(X_test_2)

In [164]:
from sklearn.multioutput import MultiOutputRegressor
from xgboost import XGBRegressor

In [165]:
xg1 = MultiOutputRegressor(XGBRegressor(n_estimators=60, learning_rate=0.03, gamma = 0, subsample=1, colsample_bytree = 1, max_depth=9)).fit(X_train_1_scaled, y_train_1)
xg2 = MultiOutputRegressor(XGBRegressor(n_estimators=60, learning_rate=0.03, gamma = 0, subsample=1, colsample_bytree = 1, max_depth=9)).fit(X_train_2_scaled, y_train_2)

In [166]:
y_pred_1 = xg1.predict(X_test_1_scaled)
y_pred_2 = xg2.predict(X_test_2_scaled)

In [167]:
y_pred_1.shape, y_pred_2.shape

((14771, 14), (24837, 14))

In [168]:
y_pred_1

array([[  1.2881064,   1.0789123,   1.0271337, ..., -21.86728  ,
        -21.864126 , -21.87517  ],
       [  1.3631651,   1.1488857,   1.0882097, ..., -21.86728  ,
        -21.864126 , -21.87517  ],
       [  1.2817712,   1.0032024,   0.9457582, ..., -21.657328 ,
        -21.650055 , -21.667646 ],
       ...,
       [  1.300969 ,   1.0290725,   0.9608718, ..., -21.848343 ,
        -21.844933 , -21.858686 ],
       [  1.2888045,   1.0157137,   0.9934472, ..., -21.848343 ,
        -21.840803 , -21.854576 ],
       [  1.3003237,   1.0779061,   0.9424626, ..., -21.848343 ,
        -21.840803 , -21.854576 ]], dtype=float32)

In [169]:
y_pred_2

array([[  1.2868135 ,   1.0128679 ,   0.9504377 , ..., -21.901545  ,
        -21.899906  , -21.903599  ],
       [  1.267886  ,   1.032631  ,   0.9597774 , ..., -21.912117  ,
        -21.909426  , -21.926727  ],
       [  1.2791768 ,   0.91240776,   1.0044539 , ..., -22.044771  ,
        -22.040695  , -22.051403  ],
       ...,
       [  1.1141579 ,   0.8686036 ,   0.8959019 , ..., -22.07026   ,
        -22.0674    , -22.07891   ],
       [  1.1101923 ,   0.82788116,   0.84342575, ..., -22.066881  ,
        -22.0674    , -22.07891   ],
       [  1.2216243 ,   0.9004961 ,   0.9032051 , ..., -22.054434  ,
        -22.048134  , -22.067533  ]], dtype=float32)

In [170]:
y_pred = np.concatenate((y_pred_1, y_pred_2), axis=0)
y_pred

array([[  1.2881064 ,   1.0789123 ,   1.0271337 , ..., -21.86728   ,
        -21.864126  , -21.87517   ],
       [  1.3631651 ,   1.1488857 ,   1.0882097 , ..., -21.86728   ,
        -21.864126  , -21.87517   ],
       [  1.2817712 ,   1.0032024 ,   0.9457582 , ..., -21.657328  ,
        -21.650055  , -21.667646  ],
       ...,
       [  1.1141579 ,   0.8686036 ,   0.8959019 , ..., -22.07026   ,
        -22.0674    , -22.07891   ],
       [  1.1101923 ,   0.82788116,   0.84342575, ..., -22.066881  ,
        -22.0674    , -22.07891   ],
       [  1.2216243 ,   0.9004961 ,   0.9032051 , ..., -22.054434  ,
        -22.048134  , -22.067533  ]], dtype=float32)

In [171]:
len(y_pred)

39608

In [172]:
submit = pd.read_csv('./DACONLG/sample_submission.csv')

In [173]:
for idx, col in enumerate(submit.columns):
    if col=='ID':
        continue
    submit[col] = y_pred[:,idx-1]
print('Done.')

Done.


In [174]:
submit.to_csv('./DACONLG/submit.csv', index=False)

In [175]:
y_pred

array([[  1.2881064 ,   1.0789123 ,   1.0271337 , ..., -21.86728   ,
        -21.864126  , -21.87517   ],
       [  1.3631651 ,   1.1488857 ,   1.0882097 , ..., -21.86728   ,
        -21.864126  , -21.87517   ],
       [  1.2817712 ,   1.0032024 ,   0.9457582 , ..., -21.657328  ,
        -21.650055  , -21.667646  ],
       ...,
       [  1.1141579 ,   0.8686036 ,   0.8959019 , ..., -22.07026   ,
        -22.0674    , -22.07891   ],
       [  1.1101923 ,   0.82788116,   0.84342575, ..., -22.066881  ,
        -22.0674    , -22.07891   ],
       [  1.2216243 ,   0.9004961 ,   0.9032051 , ..., -22.054434  ,
        -22.048134  , -22.067533  ]], dtype=float32)